build(refs T19759): use vueuse/useSortable instead of vuedraggable [vue 3 upgrade] #682
demos-europe/demosplan-ui pull request #1023
Opened 2024-09-18 13:58 UTC by salisdemos

**Ticket:** https://yaits.demos-deutschland.de/T35522

- since there is no well maintained version of `vuedraggable` that works with vue 3, we are switching to `vueuse/useSortable` (see https://vueuse.org/integrations/useSortable/)
- event parameters changed, so event handling is adjusted accordingly

2024-09-19 08:46 UTC, spiess-demos requested changes

2024-09-23 17:38 UTC, salisdemos commented on src/components/DpDataTable/DpTableHeader.vue
> +    DpResizableColumn () {
Its necessary to be loadable via `<component :is...>`. But there is another anotation wich may be more convenient. Is it better like so?
eca81abc8dd999fd82d1a5e5e9821e0f0bad1483

2024-09-23 17:39 UTC, salisdemos commented on src/components/DpDataTable/DpDataTable.vue
> +          :key="item.id">
Thanks for spotting. Changed in eca81abc8dd999fd82d1a5e5e9821e0f0bad1483

2024-09-24 15:29 UTC, salisdemos commented on src/components/DpDraggable/DpDraggable.vue
> +useSortable(
Thanks for the hint: 43d9b62d9ea00f8d1ed50b1b641524c0a9682b85

2024-09-30 09:13 UTC, spiess-demos requested changes

2024-09-30 09:13 UTC, spiess-demos commented on package.json
> +    "prosemirror-model": "1.22.3",
As a first step to clean up the versioning conflict mess, i'd suggest to get rid of direct access to prosemirror  by [changing this line](https://github.com/demos-europe/demosplan-ui/blob/e624fc6fc892dfe366d8b275bb9bc19a017f68fb/src/components/DpEditor/libs/editorInsertAtCursorPos.js#L1) to 

```
import { DOMParser } from '@tiptap/pm/model'
```

2024-10-07 07:06 UTC, spiess-demos approved these changes
lgtm (code review).

2024-10-07 07:17 UTC, merged