feat (refs DPLAN-3217 AB#12115): Refactor editable list
demos-europe/demosplan-ui pull request #1080
Opened 2024-11-14 09:13 UTC by gruenbergerdemos

### Ticket
[DPLAN-3217](https://demoseurope.youtrack.cloud/issue/DPLAN-3217)

This was already reviewed and approved for 0.3.x (see link below)

- DpInput: Also allow numbers as values
- DpEditableList: Use DpButton instead of button and use new phosphor icons instead of fontawesome

Related PR
https://github.com/demos-europe/demosplan-ui/pull/1074

2024-11-14 10:04 UTC, salisdemos requested changes
Do You think we can refactor out the parent.emits? I think this is bad practice and they should be just emits. 
(lines 148 and 154)

2024-11-14 10:04 UTC, salisdemos commented on src/components/DpEditableList/DpEditableList.vue
> +      v-if="entries.length > 0 || Object.keys(entries).length > 0"
shoudn't be thus sufficient?
```suggestion
      v-if="Object.keys(entries).length > 0"
```

2025-01-16 07:27 UTC, gruenbergerdemos commented on src/components/DpInput/DpInput.vue
> +  value?: string | number
I was also torn about that. I introduced it, because we get a number from BE, but I think we now handle that in core before giving it to the input. So we don't need it I guess.

2025-01-16 07:29 UTC, gruenbergerdemos commented
> Do You think we can refactor out the parent.emits? I think this is bad practice and they should be just emits.

I'd prefer to do this with another PR. I didn't find the time yet and I'd like to merge this.

2025-01-16 07:40 UTC, salisdemos approved these changes
Thanks!

2025-01-16 12:12 UTC, merged