feat(refs dplan 12967): fix table main
demos-europe/demosplan-ui pull request #1122
Opened 2024-12-18 12:02 UTC by gruenbergerdemos

Related PR (0.3.x)
https://github.com/demos-europe/demosplan-ui/pull/1116

2025-01-08 09:12 UTC, salisdemos requested changes

2025-01-08 09:12 UTC, salisdemos commented on src/components/DpDataTable/DpTableRow.vue
> +      :class="[{ 'c-data-table__resizable': isTruncatable }, { 'break-words': isResizable }]"
shou'nd be the class `c-data-table__resizable--truncated` even more sufficient instad of `break-words`?

2025-01-16 07:04 UTC, gruenbergerdemos commented on src/components/DpDataTable/DpTableRow.vue
> +      :class="[{ 'c-data-table__resizable': isTruncatable }, { 'break-words': isResizable }]"
It was recommended by UX to show the the whole content and not truncate it with `...` or something similar.

2025-01-16 07:44 UTC, salisdemos approved these changes

2025-01-16 07:57 UTC, merged