Refac(T32650): convert DpTableRow into a template-based component
demos-europe/demosplan-ui pull request #233
Opened 2023-05-22 08:29 UTC by sakutademos

**Ticket:** https://yaits.demos-deutschland.de/T32650

**Description:** This PR converts a functional Vue` DpTableRow` component into a template-based component. 

**IMPORTANT:** The DpTableRow component in AdministrationPlaces is not functioning properly. Although the rowData.edit parameter changes in the AdministrationPlaces component, the DOM does not update when clicking the edit button. It appears that this parameter is not being passed to DpTableRow.

It seems that the issue might be related to slots.

2023-06-06 09:11 UTC, salisdemos requested changes

2023-06-08 13:43 UTC, salisdemos requested changes
Just nitpicking

2023-06-08 13:43 UTC, salisdemos commented on src/components/core/DpDataTable/DpTableRow.vue
> +        :class="wrapped ? 'c-data-table__resizable--wrapped overflow-word-break' : 'c-data-table__resizable--truncated overflow-word-break'"
nitpick
```suggestion
        class="overflow-word-break"
        :class="wrapped ? 'c-data-table__resizable--wrapped' : 'c-data-table__resizable--truncated'"
```

2023-06-08 13:43 UTC, salisdemos commented on src/components/core/DpDataTable/DpTableRow.vue
> +          <span v-text="item[field]" v-else />
```suggestion
          <span
            v-text="item[field]"
            v-else />
```

2023-06-09 07:24 UTC, sakutademos commented on src/components/core/DpDataTable/DpTableRow.vue
> +          <span v-text="item[field]" v-else />
done here https://github.com/demos-europe/demosplan-ui/pull/233/commits/2b39dcb48f5fc71f8fa4e4e36395be699b6955bb

2023-06-09 07:24 UTC, sakutademos commented on src/components/core/DpDataTable/DpTableRow.vue
> +        :class="wrapped ? 'c-data-table__resizable--wrapped overflow-word-break' : 'c-data-table__resizable--truncated overflow-word-break'"
thx! done here https://github.com/demos-europe/demosplan-ui/pull/233/commits/2b39dcb48f5fc71f8fa4e4e36395be699b6955bb

2023-06-09 08:42 UTC, salisdemos approved these changes

2023-06-09 14:04 UTC, merged