Add dp notify message to storybook
demos-europe/demosplan-ui pull request #537
Opened 2023-09-18 14:19 UTC by ahmad-demos

- add DpNotifyMessage to Storybook.
- remove DpNotifyContainer.
- this component has already been moved to the Core.
- remove import DpNotifyContainer.

2023-09-18 14:39 UTC, spiess-demos requested changes
I propose to change two more things with this PR:

- rename component to DpNotification
- move component and its docs into ./src/DpNotification

2023-09-18 14:59 UTC, ahmad-demos commented
> I propose to change two more things with this PR:
> 
>     * rename component to DpNotification
> 
>     * move component and its docs into ./src/DpNotification

Done in https://github.com/demos-europe/demosplan-ui/pull/537/commits/f75bdde92c62acedade07a5de0f86d2442a35662

2023-09-18 15:18 UTC, spiess-demos requested changes
some nitpicks only

2023-09-18 15:18 UTC, spiess-demos commented on src/components/DpNotification/DpNotification.vue
> +import { prefixClassMixin } from '../../mixins'
```suggestion
import { prefixClassMixin } from '~/mixins'
```

2023-09-18 15:18 UTC, spiess-demos commented on tests/DpNotification.spec.js
> +import DpNotification from '~/components/DpNotification/DpNotification'
```suggestion
import DpNotification from '~/components/DpNotification'
```

2023-09-18 15:27 UTC, spiess-demos requested changes

2023-09-18 15:27 UTC, spiess-demos commented on src/components/DpNotification/DpNotification.stories.mdx
> +<dp-notify-message
```suggestion
<dp-notification
```

2023-09-18 15:27 UTC, spiess-demos commented on src/components/DpNotification/DpNotification.stories.mdx
> +The Notification component used to display brief messages or alerts to users.
```suggestion
The Notification component is used to display brief messages or alerts to users.
```

2023-09-18 15:27 UTC, spiess-demos commented on CHANGELOG.md
>  ### Changed
I think we have to mention here that the component has been renamed, which is a breaking change.

2023-09-19 07:13 UTC, spiess-demos approved these changes
nice! lgtm.

2023-09-19 10:33 UTC, merged