F move components out core folder
demos-europe/demosplan-ui pull request #651
Opened 2023-11-24 15:07 UTC by ahmad-demos

- move components from /core/ folder to root, put them in their own folders.
- adjust importing.

2023-11-27 09:00 UTC, spiess-demos requested changes
Nice! A few nitpicks, and one concern: there are 2 tests failing because of the new structure.

2023-12-04 08:24 UTC, ahmad-demos commented on CHANGELOG.md
> +- ([#651](https://github.com/demos-europe/demosplan-ui/pull/651)) Move Components from /Core/ folder to root ([@ahmad-demos](https://github.com/@ahmad-demos))
https://github.com/demos-europe/demosplan-ui/pull/651/commits/5810a05d1ec88808e38c81b19fc2bb8b00acb461

2023-12-04 08:29 UTC, ahmad-demos commented on src/components/DpEditor/DpLinkModal.vue
> +import DpModal from '../DpModal/DpModal'
https://github.com/demos-europe/demosplan-ui/pull/651/commits/37fae6ef25dda48cd295781930437ab22b65b532

2023-12-04 08:33 UTC, ahmad-demos commented on src/components/DpUpload/DpUpload.vue
https://github.com/demos-europe/demosplan-ui/pull/651/commits/eb890f81c357b8a4c5ff63e928fae9aa0987da9a

2023-12-06 12:27 UTC, spiess-demos requested changes
there are 2 test errors:

> Could not locate module ~/components/core/DpEditor/libs/handleWordPaste 
> Could not locate module ~/components/core/DpObscure.vue

2023-12-06 14:30 UTC, spiess-demos requested changes
there are still 2 test errors:

> Could not locate module ~/components/core/DpEditor/libs/handleWordPaste
> Could not locate module ~/components/core/DpObscure.vue

Please adapt paths here, as well.

2023-12-07 08:20 UTC, ahmad-demos commented
> there are still 2 test errors:
> 
> > Could not locate module ~/components/core/DpEditor/libs/handleWordPaste
> > Could not locate module ~/components/core/DpObscure.vue
> 
> Please adapt paths here, as well.

Done in https://github.com/demos-europe/demosplan-ui/pull/651/commits/b9f7544e39c4e0c6749d5a103a8efea94e61c307

2023-12-07 08:39 UTC, spiess-demos approved these changes
lgtm & works - thanks!

2023-12-07 08:55 UTC, merged