chore(refs T34290): **breaking** Always display Messages on api responses
demos-europe/demosplan-ui pull request #686
Opened 2023-12-21 14:42 UTC by salisdemos

until now, this has to be handled by the parent system. But to not forget to use it, checkResponse should always be called.

2024-10-11 15:45 UTC, spiess-demos requested changes

2024-10-11 15:45 UTC, spiess-demos commented on src/lib/DpApi.js
> +    }, options.messages || null)
Where does this "options" come from? Seems like it got removed in the signature of `doRequest` in a recent refactoring, and this was not updated accordingly.

2025-07-15 16:23 UTC, hwiem commented
Can this one be closed?

2025-07-16 06:53 UTC, salisdemos commented
Outdatend and overruled by https://github.com/demos-europe/demosplan-ui/pull/1316

2025-07-16 06:53 UTC, closed without merging