F dplan 5789 adjust input event
demos-europe/demosplan-ui pull request #832
Opened 2024-04-22 12:53 UTC by ahmad-demos

https://demoseurope.youtrack.cloud/issue/DPLAN-5789

- adjust input Event & Props.

2024-05-02 10:00 UTC, hwiem requested changes

2024-09-30 17:42 UTC, salisdemos requested changes

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpDatetimePicker/DpDatetimePicker.vue
> +        @update:model-value="$emit('update:model-value', currentDatetime)" />
```suggestion
        @update:modelValue="$emit('update:model-value', currentDatetime)" />
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpDatetimePicker/DpDatetimePicker.vue
> +        @update:model-value="$emit('update:model-value', currentDatetime)" />
```suggestion
        @update:modelValue="$emit('update:model-value', currentDatetime)" />
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpEditor/DpEditor.vue
> +  emits: ['update:model-value'],
```suggestion
  emits: ['update:modelValue'],
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpEditor/DpEditor.vue
> +      this.$emit('update:model-value', this.currentValue)
```suggestion
      this.$emit('update:modelValue', this.currentValue)
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpEditor/DpEditor.vue
> +      this.$emit('update:model-value', isEmpty ? '' : this.currentValue)
```suggestion
      this.$emit('update:modelValue', isEmpty ? '' : this.currentValue)
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpInput/DpInput.vue
> +      @input="$emit('update:model-value', currentValue)"
```suggestion
      @input="$emit('update:modelValue', currentValue)"
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpInput/DpInput.vue
> +  set: (value) => emit('update:model-value', value),
```suggestion
  set: (value) => emit('update:modelValue', value),
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpMultiselect/DpMultiselect.vue
> +      @update:model-value="newVal => $emit('update:model-value', newVal)"
```suggestion
      @update:modelValue="newVal => $emit('update:modelValue', newVal)"
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpMultiselect/DpMultiselect.vue
> +    'update:model-value',
```suggestion
    'update:modelValue',
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpMultiselect/DpMultiselect.vue
> +
Why is this necessary?

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpResettableInput/DpResettableInput.vue
> +      @update:model-value="$emit('update:model-value', currentValue)"
```suggestion
      @update:modelValue="$emit('update:modelValue', currentValue)"
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpTextArea/DpTextArea.vue
> +      @input="$emit('update:model-value', currentValue)"
```suggestion
      @input="$emit('update:modelValue', currentValue)"
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpTimePicker/DpTimePicker.vue
> +      this.$emit('update:model-value', this.currentTime)
```suggestion
      this.$emit('update:modelValue', this.currentTime)
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpToggle/DpToggle.vue
> +  emits: ['update:model-value'],
```suggestion
  emits: ['update:modelValue'],
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpToggle/DpToggle.vue
> +        this.$emit('update:model-value', !this.modelValue)
```suggestion
        this.$emit('update:modelValue', !this.modelValue)
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpTreeList/DpTreeListToggle.vue
> +  emits: ['update:model-value'],
```suggestion
  emits: ['update:modelValue'],
```

2024-09-30 17:42 UTC, salisdemos commented on src/components/DpTreeList/DpTreeListToggle.vue
> +      this.$emit('update:model-value', !this.modelValue)
```suggestion
      this.$emit('update:modelValue', !this.modelValue)
```

2024-09-30 17:45 UTC, salisdemos commented on src/components/DpDatepicker/DpDatepicker.vue
> +      this.$emit('update:model-value', valueToEmit)
```suggestion
      this.$emit('update:modelValue', valueToEmit)
```

2024-09-30 17:45 UTC, salisdemos commented on src/components/DpAutocomplete/DpAutocomplete.vue
> +      this.emit(value, 'update:model-value')
```suggestion
      this.emit(value, 'update:modelValue')
```

2024-09-30 17:45 UTC, salisdemos commented on src/components/DpDatetimePicker/DpDatetimePicker.vue
> +        @update:modelValue="$emit('update:model-value', currentDatetime)" />
```suggestion
        @update:modelValue="$emit('update:modelValue', currentDatetime)" />
```

2024-09-30 17:45 UTC, salisdemos commented on src/components/DpDatetimePicker/DpDatetimePicker.vue
> +        @update:modelValue="$emit('update:model-value', currentDatetime)" />
```suggestion
        @update:modelValue="$emit('update:modelValue', currentDatetime)" />
```

2024-09-30 17:46 UTC, salisdemos requested changes
can You please add a changelog Entry :pray:

2026-04-30 21:14 UTC, mussbach commented
@hwiem do we still need this or can it be closed?

2026-05-04 08:55 UTC, hwiem commented
> @hwiem do we still need this or can it be closed?

Thanks for bringing it up. We do need some of the changes in `main`, but I suggest closing this PR and opening a new one, there are too many conflicts.

2026-05-04 08:55 UTC, closed without merging