fix: replace the obsolete class with a tailwind class
demos-europe/demosplan-ui pull request #911
Opened 2024-06-27 09:00 UTC by sakutademos

**Description:** This PR uses the Tailwind css class `text-right` instead of the outdated `text--right`

The name `align` as a prop is not a good choice as there is a conflict with the HTML attribute `align`. The phpstrom flags it because modern HTML has deprecated this usage. Using `align` as a prop name can cause confusion since it might be interpreted as an HTML attribute.

But I am not sure which naming for the prop is better in this case? 
`textAlign`, `contentAlign`, `alignment`, `position` ? I think that the `text-alignment` is not a bad option, oder? 

![image](https://github.com/demos-europe/demosplan-ui/assets/110987766/4d25e176-b315-4fea-a4e2-99756e9cb61d)

2024-06-27 09:09 UTC, salisdemos approved these changes
Thanks for fixing!

2024-06-27 09:29 UTC, sakutademos commented
> Thanks for fixing!

There is a question about renaming the align prop :) Should I leave it as it is or rename it?

2024-06-28 08:26 UTC, salisdemos commented
> > Thanks for fixing!
> 
> There is a question about renaming the `align` prop :) What is the best option?

good question:
Maybe we can rename it like "buttonAlign" or something like that?!?

2024-07-01 09:08 UTC, spiess-demos requested changes
One concern.
As for the question on naming: how about `alignment`?

2024-07-01 09:08 UTC, spiess-demos commented on src/components/DpButtonRow/DpButtonRow.vue
> +    :class="[`text-${align}`, $attrs.class]"
Constructing the classes in such a way will stop tailwind from discovering them when parsing the source files. See https://tailwindcss.com/docs/content-configuration#dynamic-class-names

2024-07-19 10:58 UTC, spiess-demos approved these changes
lgtm!

2024-07-19 10:58 UTC, merged