feat(refs DPLAN-11981): Add image to modal
demos-europe/demosplan-ui pull request #919
Opened 2024-07-09 09:04 UTC by gruenbergerdemos

When clicking on the image to alter the alt text we also want to show the image enlarged

2024-07-15 09:02 UTC, salisdemos requested changes

2024-07-15 09:06 UTC, gruenbergerdemos commented on CHANGELOG.md
> +- ([#919](https://github.com/demos-europe/demosplan-ui/pull/919)) DpResizableImage: Disconnect image observer before destroying component ([@gruenbergerdemos](https://github.com/gruenbergerdemos))
Yes, the text is different. One is a bug fix, the other an added feature. Do you think it is confusing?

2024-07-15 09:19 UTC, salisdemos commented on CHANGELOG.md
> +- ([#919](https://github.com/demos-europe/demosplan-ui/pull/919)) DpResizableImage: Disconnect image observer before destroying component ([@gruenbergerdemos](https://github.com/gruenbergerdemos))
Yes a bit. But ok. It won't hurt.

2024-07-17 07:17 UTC, gruenbergerdemos commented on src/components/DpDataTable/DpDataTable.vue
> +          content-classes="w-fit">
Done in [ec86609](https://github.com/demos-europe/demosplan-ui/pull/919/commits/ec866092d4df684befd4e55e290da29a099d0424)

2024-07-18 14:31 UTC, salisdemos requested changes
just nitpics

2024-07-18 14:31 UTC, salisdemos commented on src/components/DpEditor/DpEditor.vue
> +      this.editingImage = imgId
```suggestion
      }

      this.editingImage = imgId
```

2024-07-18 14:45 UTC, gruenbergerdemos commented on src/components/DpEditor/DpUploadModal.vue
> +    },
Done with [8ae885d](https://github.com/demos-europe/demosplan-ui/pull/919/commits/8ae885d1214d29ebe7989e7322e87ee135191721)

2024-07-18 14:48 UTC, salisdemos approved these changes

2024-07-18 14:48 UTC, salisdemos commented on src/components/DpEditor/DpUploadModal.vue
> +      this.closeAndReset()
```suggestion

      this.closeAndReset()
```

2024-07-18 14:52 UTC, merged